[project]
name = "flask-ecs-example"
version = "0.1.0"
description = "An example of deploying an ECS Express Mode service"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "flask>=3.1.2",
]
